/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.dao.BallonDao;
import be.werkstukcp3.samgoeman.dao.BallonvaartAfspraakDao;

import be.werkstukcp3.samgoeman.dao.CrewlidDao;
import be.werkstukcp3.samgoeman.dao.KlantDao;
import be.werkstukcp3.samgoeman.dao.OpstijgterreinDao;
import be.werkstukcp3.samgoeman.dao.PilootDao;
import be.werkstukcp3.samgoeman.model.Ballon;
import be.werkstukcp3.samgoeman.model.BallonvaartAfspraak;
import be.werkstukcp3.samgoeman.model.Check;

import be.werkstukcp3.samgoeman.model.Crewlid;
import be.werkstukcp3.samgoeman.model.Design;
import be.werkstukcp3.samgoeman.model.Klant;
import be.werkstukcp3.samgoeman.model.Opstijgterrein;
import be.werkstukcp3.samgoeman.model.Piloot;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author SamGoeman
 */
public class BewerkenDialogBallonvaartAfspraak extends javax.swing.JDialog {

    private DefaultComboBoxModel<Opstijgterrein> mijnOpstijgterreinen;
    private DefaultComboBoxModel<Ballon> mijnBallonnen;

    private DefaultListModel<Crewlid> mijnCrewleden;
    private DefaultListModel<Piloot> mijnPiloten;
    private DefaultListModel<Klant> mijnKlanten;

    private Resultaat formulierResultaatBallonvaartAfspraak;

    public enum Resultaat {
        GEANNULEERD,
        TOEGEVOEGD
    }

    /**
     * Creates new form BewerkenDialogBallonvaartAfspraak
     */
    public BewerkenDialogBallonvaartAfspraak(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.getContentPane().setBackground(Design.currentColor);

        mijnOpstijgterreinen = new DefaultComboBoxModel<Opstijgterrein>();
        cbxOpstijgterrein.setModel(mijnOpstijgterreinen);

        mijnBallonnen = new DefaultComboBoxModel<Ballon>();
        cbxBallon.setModel(mijnBallonnen);

        mijnCrewleden = new DefaultListModel<Crewlid>();
        lstCrewlid.setModel(mijnCrewleden);

        mijnPiloten = new DefaultListModel<Piloot>();
        lstPiloot.setModel(mijnPiloten);

        mijnKlanten = new DefaultListModel<Klant>();
        lstKlant.setModel(mijnKlanten);
    }

    public Resultaat showDialog() {
        this.setModal(true);
        this.setVisible(true);
        return this.formulierResultaatBallonvaartAfspraak;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        btnAnnuleren = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCrewlid = new javax.swing.JList();
        txtBallonvaartAfspraakID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCrewlid = new javax.swing.JLabel();
        lblBallon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAantalPassagiers = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        lblPiloot = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKlant = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPiloot = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        cbxOpstijgterrein = new javax.swing.JComboBox();
        cbxBallon = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAnnuleren.setText("Afsluiten");
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lstCrewlid);

        txtBallonvaartAfspraakID.setEnabled(false);

        jLabel2.setText("Opstijgterrein");

        jLabel4.setText("BallonvaartAfspraakID");
        jLabel4.setToolTipText("");

        lblCrewlid.setText("Crewlid");

        lblBallon.setText("Ballon");

        jLabel3.setText("Klanten");

        txtAantalPassagiers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAantalPassagiersKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAantalPassagiersKeyReleased(evt);
            }
        });

        txtDatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumKeyReleased(evt);
            }
        });

        lblPiloot.setText("Piloot");

        jScrollPane1.setViewportView(lstKlant);

        jLabel1.setText("Aantal passagiers");

        jScrollPane2.setViewportView(lstPiloot);

        jLabel5.setText("Datum (dd/mm/jjjj)");

        jLabel11.setText("*");

        jLabel12.setText("*");

        jLabel13.setText("*");

        jLabel14.setText("*");

        jLabel15.setText("*");

        jLabel16.setText("*");

        jLabel17.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAantalPassagiers, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(txtBallonvaartAfspraakID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxOpstijgterrein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxBallon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBallon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPiloot)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCrewlid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnnuleren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBallonvaartAfspraakID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAantalPassagiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBallon)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxBallon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel16))
                                .addGap(39, 39, 39))
                            .addComponent(cbxOpstijgterrein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(39, 39, 39))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblPiloot)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCrewlid)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnnuleren)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.formulierResultaatBallonvaartAfspraak = Resultaat.TOEGEVOEGD;
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        this.formulierResultaatBallonvaartAfspraak = Resultaat.GEANNULEERD;
        this.setVisible(false);
    }//GEN-LAST:event_btnAnnulerenActionPerformed

    private void txtAantalPassagiersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAantalPassagiersKeyTyped
        Check.onlyNumberCheck(evt);
    }//GEN-LAST:event_txtAantalPassagiersKeyTyped

    private void txtAantalPassagiersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAantalPassagiersKeyReleased
       if(!Check.checkMax5Passagiers(txtAantalPassagiers.getText())){
           txtAantalPassagiers.setBackground(Color.red);
       } else {
           txtAantalPassagiers.setBackground(Color.white);
       }
    }//GEN-LAST:event_txtAantalPassagiersKeyReleased

    private void txtDatumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumKeyReleased
       if(!Check.checkDatum(txtDatum.getText())){
           txtDatum.setBackground(Color.red);
       } else {
           txtDatum.setBackground(Color.white);
       }
    }//GEN-LAST:event_txtDatumKeyReleased

    public void setTeBewerkenBallonvaartAfspraakID(int opstijgterreinID) {
        BallonvaartAfspraak teBewerkenBallonvaartAfspraak = BallonvaartAfspraakDao.getBallonvaartAfspraakById(opstijgterreinID);

        this.txtBallonvaartAfspraakID.setText(Integer.toString(teBewerkenBallonvaartAfspraak.getBallonvaartAfspraakID()));
        this.txtDatum.setText(teBewerkenBallonvaartAfspraak.getDatum());
        this.txtAantalPassagiers.setText(Integer.toString(teBewerkenBallonvaartAfspraak.getAantalPassagiers()));

        updateBallonnen();
        updateOpstijgterreinen();
        updateCrewleden();
        updateKlanten();
        updatePiloten();

        int selectedBallonID = teBewerkenBallonvaartAfspraak.getBallonID();
        Ballon geselecteerdeBallon = BallonDao.getBallonById(selectedBallonID);
        cbxBallon.setSelectedItem(geselecteerdeBallon);
        
        int selectedOpstijgterreinID = teBewerkenBallonvaartAfspraak.getOpstijgterreinID();
        Opstijgterrein geselecteerdOpstijgterrein = OpstijgterreinDao.getOpstijgterreinById(selectedOpstijgterreinID);
        cbxOpstijgterrein.setSelectedItem(geselecteerdOpstijgterrein);
        
        lstKlant.setSelectedIndex(0);
        lstPiloot.setSelectedIndex(0);
        lstCrewlid.setSelectedIndex(0);
       

    }

    public BallonvaartAfspraak getIngevuldBallonvaartAfspraak() {
        Ballon geselecteerdeBallon = (Ballon) cbxBallon.getSelectedItem();
        Opstijgterrein geselecteerdOpstijgterrein = (Opstijgterrein) cbxOpstijgterrein.getSelectedItem();

        return new BallonvaartAfspraak(Integer.parseInt(this.txtBallonvaartAfspraakID.getText()), this.txtDatum.getText(), Integer.parseInt(this.txtAantalPassagiers.getText()), geselecteerdOpstijgterrein.getOpstijgterreinID(), geselecteerdeBallon.getBallonID());
    }

    public List<Klant> getIngevuldKlantAfspraak() {
        List<Klant> mijnGeselecteerdeKlanten = lstKlant.getSelectedValuesList();
        return mijnGeselecteerdeKlanten;
    }

    public List<Crewlid> getIngevuldCrewAfspraak() {
        List<Crewlid> mijnGeselecteerdeCrewleden = lstCrewlid.getSelectedValuesList();
        return mijnGeselecteerdeCrewleden;
    }

    public List<Piloot> getIngevuldPilootAfspraak() {
        List<Piloot> mijnGeselecteerdePiloten = lstPiloot.getSelectedValuesList();
        return mijnGeselecteerdePiloten;

    }

    public void updateOpstijgterreinen() {
        mijnOpstijgterreinen.removeAllElements();
        ArrayList<Opstijgterrein> lijstVanOpstijgterreinen = OpstijgterreinDao.getOpstijgterreinen();
        for (Opstijgterrein huidigOpstijgterrein : lijstVanOpstijgterreinen) {
            mijnOpstijgterreinen.addElement(huidigOpstijgterrein);
        }
    }

    private void updateBallonnen() {
        mijnBallonnen.removeAllElements();
        ArrayList<Ballon> lijstVanBallonnen = BallonDao.getBallonnen();
        for (Ballon huidigBallon : lijstVanBallonnen) {
            mijnBallonnen.addElement(huidigBallon);
        }
    }

    public void updateKlanten() {
        mijnKlanten.clear();
        ArrayList<Klant> lijstVanKlanten = KlantDao.getKlanten();
        for (Klant huidigKlant : lijstVanKlanten) {
            mijnKlanten.addElement(huidigKlant);
        }
    }

    public void updatePiloten() {
        mijnPiloten.clear();
        ArrayList<Piloot> lijstVanPiloten = PilootDao.getPiloten();
        for (Piloot huidigPiloot : lijstVanPiloten) {
            mijnPiloten.addElement(huidigPiloot);
        }
    }

    public void updateCrewleden() {
        mijnCrewleden.clear();
        ArrayList<Crewlid> lijstVanCrewleden = CrewlidDao.getCrewleden();
        for (Crewlid huidigCrewlid : lijstVanCrewleden) {
            mijnCrewleden.addElement(huidigCrewlid);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BewerkenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BewerkenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BewerkenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BewerkenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BewerkenDialogBallonvaartAfspraak dialog = new BewerkenDialogBallonvaartAfspraak(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbxBallon;
    private javax.swing.JComboBox cbxOpstijgterrein;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBallon;
    private javax.swing.JLabel lblCrewlid;
    private javax.swing.JLabel lblPiloot;
    private javax.swing.JList lstCrewlid;
    private javax.swing.JList lstKlant;
    private javax.swing.JList lstPiloot;
    private javax.swing.JTextField txtAantalPassagiers;
    private javax.swing.JTextField txtBallonvaartAfspraakID;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables
}
