/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.dao.KlantAfspraakDao;
import be.werkstukcp3.samgoeman.dao.KlantDao;
import be.werkstukcp3.samgoeman.model.Design;
import be.werkstukcp3.samgoeman.model.Klant;
import be.werkstukcp3.samgoeman.model.KlantAfspraak;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SamGoeman
 */
public class HoofdDialogKlant extends javax.swing.JDialog {

    private DefaultListModel<Klant> mijnModel;

    /**
     * Creates new form HoofdFormulierKlant
     */
    public HoofdDialogKlant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.getContentPane().setBackground(Design.currentColor);

        mijnModel = new DefaultListModel<Klant>();
        lstKlant.setModel(mijnModel);
        lstKlant.setSelectionMode(0x0);
        updateKlantenLijst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstKlant = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnAfsluiten = new javax.swing.JButton();
        btnToevoegen = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnWijzigen = new javax.swing.JButton();
        btnVerwijderen = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lstKlant.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstKlant.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKlantValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstKlant);

        jLabel1.setText("Klanten:");

        btnAfsluiten.setText("Afsluiten");
        btnAfsluiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfsluitenActionPerformed(evt);
            }
        });

        btnToevoegen.setText("Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        btnDetails.setText("Details");
        btnDetails.setEnabled(false);
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnWijzigen.setText("Wijzigen");
        btnWijzigen.setEnabled(false);
        btnWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigenActionPerformed(evt);
            }
        });

        btnVerwijderen.setText("Selectie verwijderen");
        btnVerwijderen.setEnabled(false);
        btnVerwijderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderenActionPerformed(evt);
            }
        });

        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
        });

        jLabel2.setText("Zoek klant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerwijderen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnWijzigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel1)
                    .addComponent(btnAfsluiten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToevoegen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWijzigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerwijderen)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 22, Short.MAX_VALUE)
                .addComponent(btnAfsluiten)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateKlantenLijst() {
        mijnModel.clear();
        ArrayList<Klant> lijstVanKlanten = KlantDao.getKlanten();
        for (Klant huidigKlant : lijstVanKlanten) {
            mijnModel.addElement(huidigKlant);
        }
    }

    public void showDialog() {
        this.setVisible(true);
    }

    private void btnAfsluitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfsluitenActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAfsluitenActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        Klant weerTeGevenKlant = (Klant) lstKlant.getSelectedValue();
        DetailsDialogKlant detailsKlant = new DetailsDialogKlant(this, true);
        detailsKlant.setKlant(weerTeGevenKlant);
        detailsKlant.showDialog();
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void lstKlantValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKlantValueChanged
        if (lstKlant.isSelectionEmpty()) {
            btnVerwijderen.setEnabled(false);
            btnWijzigen.setEnabled(false);
            btnDetails.setEnabled(false);
        } else {
            btnVerwijderen.setEnabled(true);
            btnWijzigen.setEnabled(true);
            btnDetails.setEnabled(true);
        }
    }//GEN-LAST:event_lstKlantValueChanged

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        ToevoegenDialogKlant toevoegDialogKlant = new ToevoegenDialogKlant(this, true);

        ToevoegenDialogKlant.Resultaat mijnResultaatToevoegenKlant = toevoegDialogKlant.showDialog();

        if (mijnResultaatToevoegenKlant == ToevoegenDialogKlant.Resultaat.TOEGEVOEGD) {
            Klant opgehaaldKlant = toevoegDialogKlant.getIngevuldKlant();
            KlantDao.voegKlantToe(opgehaaldKlant);
            updateKlantenLijst();
        }

    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void btnWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigenActionPerformed
        Klant teWijzigenKlant = (Klant) lstKlant.getSelectedValue();

        BewerkenDialogKlant bewerkDialogKlant = new BewerkenDialogKlant(this, true);

        bewerkDialogKlant.setTeBewerkenKlantID(teWijzigenKlant.getKlantID());

        BewerkenDialogKlant.Resultaat mijnResultaatBewerkenKlant = bewerkDialogKlant.showDialog();

        if (mijnResultaatBewerkenKlant == BewerkenDialogKlant.Resultaat.TOEGEVOEGD) {
            Klant opgehaaldKlant = bewerkDialogKlant.getIngevuldKlant();
            KlantDao.updateKlant(opgehaaldKlant);
            updateKlantenLijst();
        }
    }//GEN-LAST:event_btnWijzigenActionPerformed

    private void btnVerwijderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderenActionPerformed
        Klant geselecteerdKlant = (Klant) lstKlant.getSelectedValue();
        ArrayList<KlantAfspraak> mijnKlantenAfspraken = KlantAfspraakDao.getKlantAfsprakenByKlantId(geselecteerdKlant.getKlantID());

        if (!mijnKlantenAfspraken.isEmpty()) {
            int resultaat = JOptionPane.showConfirmDialog(null, "Er hangen afspraken aan deze klant, weet u zeker dat u deze klant wilt verwijderen?", "Opgepast!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resultaat == JOptionPane.YES_OPTION) {
                KlantAfspraakDao.verwijderKlantAfspraakByKlantId(geselecteerdKlant.getKlantID());
                KlantDao.verwijderKlant(geselecteerdKlant.getKlantID());
                KlantDao.resetAutoIncrement(geselecteerdKlant.getKlantID());
            }
        } else {
            int resultaat = JOptionPane.showConfirmDialog(null, "Weet u zeker dat u deze klant wilt verwijderen?", "Opgepast!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resultaat == JOptionPane.YES_OPTION) {
                KlantDao.verwijderKlant(geselecteerdKlant.getKlantID());
                KlantDao.resetAutoIncrement(geselecteerdKlant.getKlantID());

            }
        }
        updateKlantenLijst();
    }//GEN-LAST:event_btnVerwijderenActionPerformed

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
        String input = "%" + txtInput.getText() + "%";
        ArrayList<Klant> lijstVanKlanten = KlantDao.searchKlant(input);
        mijnModel.clear();
        if (!lijstVanKlanten.isEmpty()) {
            for (Klant huidigKlant : lijstVanKlanten) {
                mijnModel.addElement(huidigKlant);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Geen klanten gevonden");
        }
    }//GEN-LAST:event_txtInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoofdDialogKlant dialog = new HoofdDialogKlant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfsluiten;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JButton btnVerwijderen;
    private javax.swing.JButton btnWijzigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstKlant;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
