/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.font.GenerateFont;
import be.werkstukcp3.samgoeman.model.Design;
import java.awt.event.KeyEvent;

/**
 *
 * @author SamGoeman
 */
public class HoofdFormulier extends javax.swing.JFrame {

    /**
     * Creates new form HoofdFormulier
     */
    public HoofdFormulier() {
        initComponents();
        setLocationRelativeTo(null);
        txtArea.setBackground(Design.currentColor);
        txtArea.setBorder(null);
        txtArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOpenOpstijgterrein = new javax.swing.JButton();
        btnKlant = new javax.swing.JButton();
        btnPiloot = new javax.swing.JButton();
        btnBallon = new javax.swing.JButton();
        btnCrewlid = new javax.swing.JButton();
        btnBallonvaartAfspraak = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Tabellen:");

        btnOpenOpstijgterrein.setText("Opstijgterrein");
        btnOpenOpstijgterrein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenOpstijgterreinActionPerformed(evt);
            }
        });

        btnKlant.setText("Klant");
        btnKlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlantActionPerformed(evt);
            }
        });

        btnPiloot.setText("Piloot");
        btnPiloot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilootActionPerformed(evt);
            }
        });

        btnBallon.setText("SponsorContract");
        btnBallon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallonActionPerformed(evt);
            }
        });

        btnCrewlid.setText("Crewlid");
        btnCrewlid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrewlidActionPerformed(evt);
            }
        });

        btnBallonvaartAfspraak.setText("Ballonvaart afspraak");
        btnBallonvaartAfspraak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBallonvaartAfspraakActionPerformed(evt);
            }
        });

        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        jLabel2.setText("Uitleg:");

        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setText("Voor een ballonvaart afspraak toe te voegen\nklik op ballonvaart afspraak.\n\nSponsorContract bevat de ballonnen en sponsors.\n\nPiloot, crewlid, klant en opstijgterrein kan je bekijken\ntoevoegen, bewerken of verwijderen.\n\nIndien u een ander font of kleur had gewenst\ngelieve bij settings dit aan te passen.");
        txtArea.setBorder(null);
        txtArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAreaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKlant, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrewlid, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPiloot, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSettings)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAbout))
                        .addComponent(btnOpenOpstijgterrein, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBallon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBallonvaartAfspraak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBallonvaartAfspraak, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBallon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPiloot, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrewlid, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKlant, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnOpenOpstijgterrein, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenOpstijgterreinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenOpstijgterreinActionPerformed
        HoofdDialogOpstijgterrein dialoogOpstijgterrein = new HoofdDialogOpstijgterrein(this, true);
        dialoogOpstijgterrein.showDialog();
    }//GEN-LAST:event_btnOpenOpstijgterreinActionPerformed

    private void btnKlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlantActionPerformed
       HoofdDialogKlant dialoogKlant = new HoofdDialogKlant(this, true);
        dialoogKlant.getContentPane().setBackground(Design.currentColor);
        dialoogKlant.showDialog();
    }//GEN-LAST:event_btnKlantActionPerformed

    private void btnPilootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilootActionPerformed
        HoofdDialogPiloot dialoogPiloot = new HoofdDialogPiloot(this, true);
        dialoogPiloot.getContentPane().setBackground(Design.currentColor);
        dialoogPiloot.showDialog();
    }//GEN-LAST:event_btnPilootActionPerformed

    private void btnBallonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallonActionPerformed
        HoofdDialogSponsorContract dialoogBallon = new HoofdDialogSponsorContract(this, true);
        dialoogBallon.showDialog();
    }//GEN-LAST:event_btnBallonActionPerformed

    private void btnCrewlidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrewlidActionPerformed
        HoofdDialogCrewlid dialoogCrewlid = new HoofdDialogCrewlid(this, true);
        dialoogCrewlid.showDialog();
    }//GEN-LAST:event_btnCrewlidActionPerformed

    private void btnBallonvaartAfspraakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBallonvaartAfspraakActionPerformed
        HoofdDialogBallonvaartAfspraak dialoogBallonvaartAfspraak = new HoofdDialogBallonvaartAfspraak(this, true);
        dialoogBallonvaartAfspraak.showDialog();
    }//GEN-LAST:event_btnBallonvaartAfspraakActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true);
        aboutDialog.showDialog();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        SettingDailog settingDialog = new SettingDailog(this, true);
        settingDialog.showDialog();
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Design.currentColor);
        btnAbout.setFont(Design.currentFont);
        txtArea.setBackground(Design.currentColor);
        btnBallon.setFont(Design.currentFont);
        btnBallonvaartAfspraak.setFont(Design.currentFont);
        btnCrewlid.setFont(Design.currentFont);
        btnKlant.setFont(Design.currentFont);
        btnOpenOpstijgterrein.setFont(Design.currentFont);
        btnPiloot.setFont(Design.currentFont);
        btnSettings.setFont(Design.currentFont);
        jLabel1.setFont(Design.currentFont);
        jLabel2.setFont(Design.currentFont);
        txtArea.setFont(Design.currentFont);
    }//GEN-LAST:event_formWindowActivated

    private void txtAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyTyped
        
    }//GEN-LAST:event_txtAreaKeyTyped

    private void txtAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyReleased
        
    }//GEN-LAST:event_txtAreaKeyReleased

    private void txtAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaKeyPressed
        
    }//GEN-LAST:event_txtAreaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoofdFormulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoofdFormulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoofdFormulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoofdFormulier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoofdFormulier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBallon;
    private javax.swing.JButton btnBallonvaartAfspraak;
    private javax.swing.JButton btnCrewlid;
    private javax.swing.JButton btnKlant;
    private javax.swing.JButton btnOpenOpstijgterrein;
    private javax.swing.JButton btnPiloot;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
