/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.dao.BallonvaartAfspraakDao;
import be.werkstukcp3.samgoeman.dao.CrewAfspraakDao;
import be.werkstukcp3.samgoeman.dao.KlantAfspraakDao;
import be.werkstukcp3.samgoeman.dao.PilootAfspraakDao;
import be.werkstukcp3.samgoeman.model.BallonvaartAfspraak;
import be.werkstukcp3.samgoeman.model.CrewAfspraak;
import be.werkstukcp3.samgoeman.model.Crewlid;
import be.werkstukcp3.samgoeman.model.Design;
import be.werkstukcp3.samgoeman.model.Klant;
import be.werkstukcp3.samgoeman.model.KlantAfspraak;
import be.werkstukcp3.samgoeman.model.Piloot;
import be.werkstukcp3.samgoeman.model.PilootAfspraak;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SamGoeman
 */
public class HoofdDialogBallonvaartAfspraak extends javax.swing.JDialog {

    private DefaultListModel<BallonvaartAfspraak> mijnModel;

    /**
     * Creates new form HoofdFormulierBallonvaartAfspraak
     */
    public HoofdDialogBallonvaartAfspraak(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.getContentPane().setBackground(Design.currentColor);

        mijnModel = new DefaultListModel<BallonvaartAfspraak>();
        lstBallonvaartAfspraak.setModel(mijnModel);
        lstBallonvaartAfspraak.setSelectionMode(0x0);
        updateBallonvaartAfsprakenLijst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstBallonvaartAfspraak = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnAfsluiten = new javax.swing.JButton();
        btnToevoegen = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnWijzigen = new javax.swing.JButton();
        btnVerwijderen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lstBallonvaartAfspraak.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstBallonvaartAfspraak.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstBallonvaartAfspraakValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstBallonvaartAfspraak);

        jLabel1.setText("Ballonvaart afspraken:");

        btnAfsluiten.setText("Afsluiten");
        btnAfsluiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfsluitenActionPerformed(evt);
            }
        });

        btnToevoegen.setText("Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        btnDetails.setText("Details");
        btnDetails.setEnabled(false);
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnWijzigen.setText("Wijzigen");
        btnWijzigen.setEnabled(false);
        btnWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigenActionPerformed(evt);
            }
        });

        btnVerwijderen.setText("Selectie verwijderen");
        btnVerwijderen.setEnabled(false);
        btnVerwijderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerwijderen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWijzigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addComponent(btnAfsluiten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToevoegen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWijzigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerwijderen)))
                .addGap(18, 18, 18)
                .addComponent(btnAfsluiten)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateBallonvaartAfsprakenLijst() {
        mijnModel.clear();
        ArrayList<BallonvaartAfspraak> lijstVanBallonvaartAfspraaken = BallonvaartAfspraakDao.getBallonvaartAfspraken();
        for (BallonvaartAfspraak huidigBallonvaartAfspraak : lijstVanBallonvaartAfspraaken) {
            mijnModel.addElement(huidigBallonvaartAfspraak);
        }
    }

    public void showDialog() {
        this.setVisible(true);
    }

    private void btnAfsluitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfsluitenActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAfsluitenActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        BallonvaartAfspraak weerTeGevenBallonvaartAfspraak = (BallonvaartAfspraak) lstBallonvaartAfspraak.getSelectedValue();
        DetailsDialogBallonvaartAfspraak detailsBallonvaartAfspraak = new DetailsDialogBallonvaartAfspraak(this, true);
        detailsBallonvaartAfspraak.setBallonvaartAfspraak(weerTeGevenBallonvaartAfspraak);
        detailsBallonvaartAfspraak.showDialog();
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void lstBallonvaartAfspraakValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstBallonvaartAfspraakValueChanged
        if (lstBallonvaartAfspraak.isSelectionEmpty()) {
            btnVerwijderen.setEnabled(false);
            btnWijzigen.setEnabled(false);
            btnDetails.setEnabled(false);
        } else {
            btnVerwijderen.setEnabled(true);
            btnWijzigen.setEnabled(true);
            btnDetails.setEnabled(true);
        }
    }//GEN-LAST:event_lstBallonvaartAfspraakValueChanged

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        ToevoegenDialogBallonvaartAfspraak toevoegDialogBallonvaartAfspraak = new ToevoegenDialogBallonvaartAfspraak(this, true);

        ToevoegenDialogBallonvaartAfspraak.Resultaat mijnResultaatToevoegenBallonvaartAfspraak = toevoegDialogBallonvaartAfspraak.showDialog();

        if (mijnResultaatToevoegenBallonvaartAfspraak == ToevoegenDialogBallonvaartAfspraak.Resultaat.TOEGEVOEGD) {

            BallonvaartAfspraak opgehaaldBallonvaartAfspraak = toevoegDialogBallonvaartAfspraak.getIngevuldBallonvaartAfspraak();
            BallonvaartAfspraakDao.voegBallonvaartAfspraakToe(opgehaaldBallonvaartAfspraak);

            //id ophalen van laatst toegevoegde BallonvaartAfspraak
            ArrayList getLijst = BallonvaartAfspraakDao.getBallonvaartAfspraken();
            BallonvaartAfspraak lastBallonvaartAfspraak = (BallonvaartAfspraak) getLijst.get(getLijst.size() - 1);

            //Crewlid afspraken toevoegen
            List<Crewlid> mijnOpgehaaldeCrewleden = toevoegDialogBallonvaartAfspraak.getIngevuldCrewAfspraak();

            for (Crewlid crewlid : mijnOpgehaaldeCrewleden) {
                CrewAfspraak nieuwCrewAfspraak = new CrewAfspraak(0, lastBallonvaartAfspraak.getBallonvaartAfspraakID(), crewlid.getCrewlidID());
                CrewAfspraakDao.voegCrewAfspraakToe(nieuwCrewAfspraak);
            }

            //Klanten afspraken toevoegen
            List<Klant> mijnOpgehaaldeKlanten = toevoegDialogBallonvaartAfspraak.getIngevuldKlantAfspraak();

            for (Klant klant : mijnOpgehaaldeKlanten) {
                KlantAfspraak nieuweKlantAfspraak = new KlantAfspraak(0, lastBallonvaartAfspraak.getBallonvaartAfspraakID(), klant.getKlantID());
                KlantAfspraakDao.voegKlantAfspraakToe(nieuweKlantAfspraak);
            }

            //Piloot afspraken toevoegen
            List<Piloot> mijnOpgehaaldePiloten = toevoegDialogBallonvaartAfspraak.getIngevuldPilootAfspraak();

            for (Piloot piloot : mijnOpgehaaldePiloten) {
                PilootAfspraak nieuwePilootAfspraak = new PilootAfspraak(0, lastBallonvaartAfspraak.getBallonvaartAfspraakID(), piloot.getPilootID());
                PilootAfspraakDao.voegPilootAfspraakToe(nieuwePilootAfspraak);
            }

            updateBallonvaartAfsprakenLijst();

        }

    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void btnWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigenActionPerformed
        BallonvaartAfspraak teWijzigenBallonvaartAfspraak = (BallonvaartAfspraak) lstBallonvaartAfspraak.getSelectedValue();

        BewerkenDialogBallonvaartAfspraak bewerkDialogBallonvaartAfspraak = new BewerkenDialogBallonvaartAfspraak(this, true);

        bewerkDialogBallonvaartAfspraak.setTeBewerkenBallonvaartAfspraakID(teWijzigenBallonvaartAfspraak.getBallonvaartAfspraakID());

        BewerkenDialogBallonvaartAfspraak.Resultaat mijnResultaatBewerkenBallonvaartAfspraak = bewerkDialogBallonvaartAfspraak.showDialog();

        if (mijnResultaatBewerkenBallonvaartAfspraak == BewerkenDialogBallonvaartAfspraak.Resultaat.TOEGEVOEGD) {
            BallonvaartAfspraak opgehaaldBallonvaartAfspraak = bewerkDialogBallonvaartAfspraak.getIngevuldBallonvaartAfspraak();
            BallonvaartAfspraakDao.updateBallonvaartAfspraak(opgehaaldBallonvaartAfspraak);

            int opgehaaldeBallonvaartAfspraakID = opgehaaldBallonvaartAfspraak.getBallonvaartAfspraakID();

            //Crewlid afspraken updaten
            List<Crewlid> mijnOpgehaaldeCrewleden = bewerkDialogBallonvaartAfspraak.getIngevuldCrewAfspraak();

            //eerst allemaal verwijderen, daarna opnieuw invoeren
            CrewAfspraakDao.verwijderCrewAfspraakByBallonvaartAfspraakId(opgehaaldeBallonvaartAfspraakID);

            for (Crewlid crewlid : mijnOpgehaaldeCrewleden) {
                CrewAfspraak nieuwCrewAfspraak = new CrewAfspraak(0, opgehaaldeBallonvaartAfspraakID, crewlid.getCrewlidID());
                CrewAfspraakDao.voegCrewAfspraakToe(nieuwCrewAfspraak);
            }

            //Klanten afspraken updaten
            KlantAfspraakDao.verwijderKlantAfspraakByBallonvaartAfspraakId(opgehaaldeBallonvaartAfspraakID);

            List<Klant> mijnOpgehaaldeKlanten = bewerkDialogBallonvaartAfspraak.getIngevuldKlantAfspraak();

            for (Klant klant : mijnOpgehaaldeKlanten) {
                KlantAfspraak nieuweKlantAfspraak = new KlantAfspraak(0, opgehaaldeBallonvaartAfspraakID, klant.getKlantID());
                KlantAfspraakDao.voegKlantAfspraakToe(nieuweKlantAfspraak);
            }

            //Piloot afspraken udpaten
            PilootAfspraakDao.verwijderPilootAfspraakByBallonvaartAfspraakId(opgehaaldeBallonvaartAfspraakID);

            List<Piloot> mijnOpgehaaldePiloten = bewerkDialogBallonvaartAfspraak.getIngevuldPilootAfspraak();

            for (Piloot piloot : mijnOpgehaaldePiloten) {
                PilootAfspraak nieuwePilootAfspraak = new PilootAfspraak(0, opgehaaldeBallonvaartAfspraakID, piloot.getPilootID());
                PilootAfspraakDao.voegPilootAfspraakToe(nieuwePilootAfspraak);
            }

        }

        updateBallonvaartAfsprakenLijst();
    }//GEN-LAST:event_btnWijzigenActionPerformed

    private void btnVerwijderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderenActionPerformed
        BallonvaartAfspraak geselecteerdBallonvaartAfspraak = (BallonvaartAfspraak) lstBallonvaartAfspraak.getSelectedValue();

        int geselecteerdBallonvaartAfspraakID = geselecteerdBallonvaartAfspraak.getBallonvaartAfspraakID();
        int resultaat = JOptionPane.showConfirmDialog(null, "Weet u zeker dat u deze ballonvaart afspraak wilt verwijderen?", "Opgepast!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resultaat == JOptionPane.YES_OPTION) {
            CrewAfspraakDao.verwijderCrewAfspraakByBallonvaartAfspraakId(geselecteerdBallonvaartAfspraakID);
            KlantAfspraakDao.verwijderKlantAfspraakByBallonvaartAfspraakId(geselecteerdBallonvaartAfspraakID);
            PilootAfspraakDao.verwijderPilootAfspraakByBallonvaartAfspraakId(geselecteerdBallonvaartAfspraakID);
            BallonvaartAfspraakDao.verwijderBallonvaartAfspraak(geselecteerdBallonvaartAfspraakID);

            CrewAfspraakDao.resetAutoIncrement(geselecteerdBallonvaartAfspraakID);
            KlantAfspraakDao.resetAutoIncrement(geselecteerdBallonvaartAfspraakID);
            PilootAfspraakDao.resetAutoIncrement(geselecteerdBallonvaartAfspraakID);
            BallonvaartAfspraakDao.resetAutoIncrement(geselecteerdBallonvaartAfspraakID);
        }
        updateBallonvaartAfsprakenLijst();
    }//GEN-LAST:event_btnVerwijderenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoofdDialogBallonvaartAfspraak dialog = new HoofdDialogBallonvaartAfspraak(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfsluiten;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JButton btnVerwijderen;
    private javax.swing.JButton btnWijzigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstBallonvaartAfspraak;
    // End of variables declaration//GEN-END:variables
}
