/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.dao.PilootAfspraakDao;
import be.werkstukcp3.samgoeman.dao.PilootDao;
import be.werkstukcp3.samgoeman.model.Design;
import be.werkstukcp3.samgoeman.model.Piloot;
import be.werkstukcp3.samgoeman.model.PilootAfspraak;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SamGoeman
 */
public class HoofdDialogPiloot extends javax.swing.JDialog {

    private DefaultListModel<Piloot> mijnModel;

    /**
     * Creates new form HoofdFormulierPiloot
     */
    public HoofdDialogPiloot(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.getContentPane().setBackground(Design.currentColor);

        mijnModel = new DefaultListModel<Piloot>();
        lstPiloot.setModel(mijnModel);
        lstPiloot.setSelectionMode(0x0);
        updatePilotenLijst();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstPiloot = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnAfsluiten = new javax.swing.JButton();
        btnToevoegen = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnWijzigen = new javax.swing.JButton();
        btnVerwijderen = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lstPiloot.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstPiloot.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPilootValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPiloot);

        jLabel1.setText("Klanten:");

        btnAfsluiten.setText("Afsluiten");
        btnAfsluiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfsluitenActionPerformed(evt);
            }
        });

        btnToevoegen.setText("Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        btnDetails.setText("Details");
        btnDetails.setEnabled(false);
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnWijzigen.setText("Wijzigen");
        btnWijzigen.setEnabled(false);
        btnWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigenActionPerformed(evt);
            }
        });

        btnVerwijderen.setText("Selectie verwijderen");
        btnVerwijderen.setEnabled(false);
        btnVerwijderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerwijderenActionPerformed(evt);
            }
        });

        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInputKeyReleased(evt);
            }
        });

        jLabel2.setText("Zoek piloot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerwijderen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWijzigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))))
                    .addComponent(jLabel1)
                    .addComponent(btnAfsluiten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnToevoegen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWijzigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerwijderen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnAfsluiten)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updatePilotenLijst() {
        mijnModel.clear();
        ArrayList<Piloot> lijstVanPilooten = PilootDao.getPiloten();
        for (Piloot huidigPiloot : lijstVanPilooten) {
            mijnModel.addElement(huidigPiloot);
        }
    }

    public void showDialog() {
        this.setVisible(true);
    }

    private void btnAfsluitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfsluitenActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnAfsluitenActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        Piloot weerTeGevenPiloot = (Piloot) lstPiloot.getSelectedValue();
        DetailsDialogPiloot detailsPiloot = new DetailsDialogPiloot(this, true);
        detailsPiloot.setPiloot(weerTeGevenPiloot);
        detailsPiloot.showDialog();
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void lstPilootValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPilootValueChanged
        if (lstPiloot.isSelectionEmpty()) {
            btnVerwijderen.setEnabled(false);
            btnWijzigen.setEnabled(false);
            btnDetails.setEnabled(false);
        } else {
            btnVerwijderen.setEnabled(true);
            btnWijzigen.setEnabled(true);
            btnDetails.setEnabled(true);
        }
    }//GEN-LAST:event_lstPilootValueChanged

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        ToevoegenDialogPiloot toevoegDialogPiloot = new ToevoegenDialogPiloot(this, true);

        ToevoegenDialogPiloot.Resultaat mijnResultaatToevoegenPiloot = toevoegDialogPiloot.showDialog();

        if (mijnResultaatToevoegenPiloot == ToevoegenDialogPiloot.Resultaat.TOEGEVOEGD) {
            Piloot opgehaaldPiloot = toevoegDialogPiloot.getIngevuldPiloot();
            PilootDao.voegPilootToe(opgehaaldPiloot);
            updatePilotenLijst();
        }

    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void btnWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigenActionPerformed
        Piloot teWijzigenPiloot = (Piloot) lstPiloot.getSelectedValue();

        BewerkenDialogPiloot bewerkDialogPiloot = new BewerkenDialogPiloot(this, true);

        bewerkDialogPiloot.setTeBewerkenPilootID(teWijzigenPiloot.getPilootID());

        BewerkenDialogPiloot.Resultaat mijnResultaatBewerkenPiloot = bewerkDialogPiloot.showDialog();

        if (mijnResultaatBewerkenPiloot == BewerkenDialogPiloot.Resultaat.TOEGEVOEGD) {
            Piloot opgehaaldPiloot = bewerkDialogPiloot.getIngevuldPiloot();
            PilootDao.updatePiloot(opgehaaldPiloot);
            updatePilotenLijst();
        }
    }//GEN-LAST:event_btnWijzigenActionPerformed

    private void btnVerwijderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerwijderenActionPerformed
        Piloot geselecteerdPiloot = (Piloot) lstPiloot.getSelectedValue();
        ArrayList<PilootAfspraak> mijnPilootAfspraken = PilootAfspraakDao.getPilootAfsprakenByPilootId(geselecteerdPiloot.getPilootID());

        if (!mijnPilootAfspraken.isEmpty()) {
            int resultaat = JOptionPane.showConfirmDialog(null, "Er hangen afspraken aan deze piloot, weet u zeker dat u deze piloot wilt verwijderen?", "Opgepast!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resultaat == JOptionPane.YES_OPTION) {
                PilootAfspraakDao.verwijderPilootAfspraakByPilootId(geselecteerdPiloot.getPilootID());
                PilootDao.verwijderPiloot(geselecteerdPiloot.getPilootID());
                PilootDao.resetAutoIncrement(geselecteerdPiloot.getPilootID());
            }
        } else {
            int resultaat = JOptionPane.showConfirmDialog(null, "Weet u zeker dat u deze piloot wilt verwijderen?", "Opgepast!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (resultaat == JOptionPane.YES_OPTION) {
                PilootDao.verwijderPiloot(geselecteerdPiloot.getPilootID());
                PilootDao.resetAutoIncrement(geselecteerdPiloot.getPilootID());
            }
        }
        updatePilotenLijst();
    }//GEN-LAST:event_btnVerwijderenActionPerformed

    private void txtInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyReleased
        String input = "%" + txtInput.getText() + "%";
        ArrayList<Piloot> lijstVanPiloten = PilootDao.searchPiloot(input);
        mijnModel.clear();
        if (!lijstVanPiloten.isEmpty()) {
            for (Piloot huidigPiloot : lijstVanPiloten) {
                mijnModel.addElement(huidigPiloot);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Geen piloten gevonden");
        }
    }//GEN-LAST:event_txtInputKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogPiloot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogPiloot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogPiloot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoofdDialogPiloot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoofdDialogPiloot dialog = new HoofdDialogPiloot(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfsluiten;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JButton btnVerwijderen;
    private javax.swing.JButton btnWijzigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstPiloot;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
