/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.font.GenerateFont;
import be.werkstukcp3.samgoeman.model.Design;
import java.awt.Font;

/**
 *
 * @author SamGoeman
 */
public class SettingDailog extends javax.swing.JDialog {

    /**
     * Creates new form HoofdFormulierPiloot
     */
    public SettingDailog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.getContentPane().setBackground(Design.currentColor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgFont = new javax.swing.ButtonGroup();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdbRaleway = new javax.swing.JRadioButton();
        rdbCutive = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnKleur1 = new javax.swing.JButton();
        btnKleur2 = new javax.swing.JButton();
        btnKleur3 = new javax.swing.JButton();
        rdbDefault = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Klik op onderstaande kleuren voor alle frames deze kleur te geven");

        btgFont.add(rdbRaleway);
        rdbRaleway.setText("Raleway");
        rdbRaleway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRalewayActionPerformed(evt);
            }
        });

        btgFont.add(rdbCutive);
        rdbCutive.setText("Cutive Mono");
        rdbCutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCutiveActionPerformed(evt);
            }
        });

        jLabel2.setText("Kies het font voor deze applicatie");

        btnKleur1.setBackground(new java.awt.Color(236, 240, 241));
        btnKleur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKleur1ActionPerformed(evt);
            }
        });

        btnKleur2.setBackground(new java.awt.Color(236, 100, 75));
        btnKleur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKleur2ActionPerformed(evt);
            }
        });

        btnKleur3.setBackground(new java.awt.Color(135, 211, 124));
        btnKleur3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKleur3ActionPerformed(evt);
            }
        });

        btgFont.add(rdbDefault);
        rdbDefault.setText("Default");
        rdbDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbRaleway)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCutive)
                        .addGap(18, 18, 18)
                        .addComponent(rdbDefault))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKleur1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKleur3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKleur2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbRaleway)
                    .addComponent(rdbCutive)
                    .addComponent(rdbDefault))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKleur1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKleur2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKleur3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showDialog() {
        this.setVisible(true);
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void rdbRalewayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRalewayActionPerformed
        // TODO add your handling code here:
        if (rdbRaleway.isSelected()) {
            Design.currentFont = GenerateFont.raleway12();
        } 
    }//GEN-LAST:event_rdbRalewayActionPerformed

    private void rdbCutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCutiveActionPerformed
        if (rdbCutive.isSelected()) {
            Design.currentFont = GenerateFont.cutive12();
        } 
    }//GEN-LAST:event_rdbCutiveActionPerformed

    private void btnKleur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKleur1ActionPerformed
        Design.currentColor = btnKleur1.getBackground();
    }//GEN-LAST:event_btnKleur1ActionPerformed

    private void btnKleur3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKleur3ActionPerformed
        Design.currentColor = btnKleur3.getBackground();
    }//GEN-LAST:event_btnKleur3ActionPerformed

    private void btnKleur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKleur2ActionPerformed
        // TODO add your handling code here:
        Design.currentColor = btnKleur2.getBackground();
    }//GEN-LAST:event_btnKleur2ActionPerformed

    private void rdbDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDefaultActionPerformed
        if (rdbDefault.isSelected()) {
            Design.currentFont = new Font("Lucida Grande", Font.PLAIN, 12);
        } 
    }//GEN-LAST:event_rdbDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingDailog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingDailog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingDailog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingDailog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingDailog dialog = new SettingDailog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgFont;
    private javax.swing.JButton btnKleur1;
    private javax.swing.JButton btnKleur2;
    private javax.swing.JButton btnKleur3;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rdbCutive;
    private javax.swing.JRadioButton rdbDefault;
    private javax.swing.JRadioButton rdbRaleway;
    // End of variables declaration//GEN-END:variables
}
