/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.werkstukcp3.samgoeman.swing;

import be.werkstukcp3.samgoeman.dao.BallonDao;
import be.werkstukcp3.samgoeman.dao.CrewlidDao;
import be.werkstukcp3.samgoeman.dao.KlantDao;
import be.werkstukcp3.samgoeman.dao.OpstijgterreinDao;
import be.werkstukcp3.samgoeman.dao.PilootDao;
import be.werkstukcp3.samgoeman.model.Ballon;
import be.werkstukcp3.samgoeman.model.BallonvaartAfspraak;
import be.werkstukcp3.samgoeman.model.Check;
import be.werkstukcp3.samgoeman.model.Crewlid;

import be.werkstukcp3.samgoeman.model.Design;
import be.werkstukcp3.samgoeman.model.Klant;
import be.werkstukcp3.samgoeman.model.Opstijgterrein;
import be.werkstukcp3.samgoeman.model.Piloot;
import java.awt.Color;

import java.util.ArrayList;
import java.util.List;


import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author SamGoeman
 */
public class ToevoegenDialogBallonvaartAfspraak extends javax.swing.JDialog {

    public enum Resultaat {
        GEANNULEERD,
        TOEGEVOEGD
    }

    private Resultaat formulierResultaatBallonvaartAfspraak;
    private DefaultComboBoxModel<Opstijgterrein> mijnOpstijgterreinen;
    private DefaultComboBoxModel<Ballon> mijnBallonnen;

    private DefaultListModel<Klant> mijnKlanten;
    private DefaultListModel<Piloot> mijnPiloten;
    private DefaultListModel<Crewlid> mijnCrewleden;

    private String datum;

    /**
     * Creates new form ToevoegenDialogBallonvaartAfspraak
     */
    public ToevoegenDialogBallonvaartAfspraak(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.getContentPane().setBackground(Design.currentColor);

        mijnOpstijgterreinen = new DefaultComboBoxModel<Opstijgterrein>();
        cbxOpstijgterrein.setModel(mijnOpstijgterreinen);
        updateOpstijgterreinen();

        mijnBallonnen = new DefaultComboBoxModel<Ballon>();
        cbxBallon.setModel(mijnBallonnen);
        updateBallonnen();

        mijnKlanten = new DefaultListModel<Klant>();
        lstKlant.setModel(mijnKlanten);
        updateKlanten();

        mijnPiloten = new DefaultListModel<Piloot>();
        lstPiloot.setModel(mijnPiloten);
        updatePiloten();

        mijnCrewleden = new DefaultListModel<Crewlid>();
        lstCrewlid.setModel(mijnCrewleden);
        updateCrewleden();
        

    }

    public Resultaat showDialog() {
        this.setModal(true);
        this.setVisible(true);
        return this.formulierResultaatBallonvaartAfspraak;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDatum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAantalPassagiers = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAnnuleren = new javax.swing.JButton();
        btnToevoegen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbxOpstijgterrein = new javax.swing.JComboBox();
        cbxBallon = new javax.swing.JComboBox();
        lblBallon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKlant = new javax.swing.JList<>();
        lblPiloot = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPiloot = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCrewlid = new javax.swing.JList<>();
        lblCrewlid = new javax.swing.JLabel();
        lblWarningPassagiers = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txtDatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumKeyReleased(evt);
            }
        });

        jLabel5.setText("Datum (dd/mm/jjjj)");

        txtAantalPassagiers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAantalPassagiersKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAantalPassagiersKeyReleased(evt);
            }
        });

        jLabel1.setText("Aantal passagiers");

        btnAnnuleren.setText("Afsluiten");
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        btnToevoegen.setText("Toevoegen");
        btnToevoegen.setEnabled(false);
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        jLabel2.setText("Opstijgterrein");

        lblBallon.setText("Ballon");

        jLabel3.setText("Klanten");

        lstKlant.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstKlantValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstKlant);

        lblPiloot.setText("Piloot");

        lstPiloot.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPilootValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPiloot);

        lstCrewlid.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCrewlidValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCrewlid);

        lblCrewlid.setText("Crewlid");

        jLabel4.setText("*");

        jLabel6.setText("*");

        jLabel7.setText("*");

        jLabel8.setText("*");

        jLabel9.setText("*");

        jLabel10.setText("*");

        jLabel11.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAnnuleren, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnToevoegen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPiloot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCrewlid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblWarningPassagiers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAantalPassagiers)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxBallon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBallon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxOpstijgterrein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(119, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(16, 16, 16)
                                .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBallon)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxBallon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAantalPassagiers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxOpstijgterrein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarningPassagiers, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblPiloot)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCrewlid)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnToevoegen)
                .addGap(18, 18, 18)
                .addComponent(btnAnnuleren)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        this.formulierResultaatBallonvaartAfspraak = Resultaat.GEANNULEERD;
        this.setVisible(false);
    }//GEN-LAST:event_btnAnnulerenActionPerformed

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        this.formulierResultaatBallonvaartAfspraak = Resultaat.TOEGEVOEGD;
        this.setVisible(false);
    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void txtDatumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumKeyReleased
        datum = txtDatum.getText();
        if (!(Check.checkDatum(datum))) {
            txtDatum.setBackground(Color.red);
        } else {
            txtDatum.setBackground(Color.white);
        }
        checkFields();
    }//GEN-LAST:event_txtDatumKeyReleased

    private void txtAantalPassagiersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAantalPassagiersKeyReleased
        boolean checkPassagiers = Check.checkMax5Passagiers(txtAantalPassagiers.getText());

        if (!checkPassagiers) {
            txtAantalPassagiers.setBackground(Color.red);
            lblWarningPassagiers.setText("Max 5 passagiers");
        } else {
            txtAantalPassagiers.setBackground(Color.white);
            lblWarningPassagiers.setText("");
        }

        checkFields();
    }//GEN-LAST:event_txtAantalPassagiersKeyReleased

    private void txtAantalPassagiersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAantalPassagiersKeyTyped
        Check.onlyNumberCheck(evt);
    }//GEN-LAST:event_txtAantalPassagiersKeyTyped

    private void lstKlantValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstKlantValueChanged
        checkFields();
    }//GEN-LAST:event_lstKlantValueChanged

    private void lstPilootValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPilootValueChanged
        checkFields();
    }//GEN-LAST:event_lstPilootValueChanged

    private void lstCrewlidValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCrewlidValueChanged
        checkFields();
    }//GEN-LAST:event_lstCrewlidValueChanged
    private void updateOpstijgterreinen() {
        mijnOpstijgterreinen.removeAllElements();
        ArrayList<Opstijgterrein> lijstVanOpstijgterreinen = OpstijgterreinDao.getOpstijgterreinen();
        for (Opstijgterrein huidigOpstijgterrein : lijstVanOpstijgterreinen) {
            mijnOpstijgterreinen.addElement(huidigOpstijgterrein);
        }
    }

    private void updateBallonnen() {
        mijnBallonnen.removeAllElements();
        ArrayList<Ballon> lijstVanBallonnen = BallonDao.getBallonnen();
        for (Ballon huidigBallon : lijstVanBallonnen) {
            mijnBallonnen.addElement(huidigBallon);
        }
    }

    private void updateKlanten() {
        mijnKlanten.clear();
        ArrayList<Klant> lijstVanKlanten = KlantDao.getKlanten();
        for (Klant huidigKlant : lijstVanKlanten) {
            mijnKlanten.addElement(huidigKlant);
        }
    }

    private void updatePiloten() {
        mijnPiloten.clear();
        ArrayList<Piloot> lijstVanPiloten = PilootDao.getPiloten();
        for (Piloot huidigPiloot : lijstVanPiloten) {
            mijnPiloten.addElement(huidigPiloot);
        }
    }

    private void updateCrewleden() {
        mijnCrewleden.clear();
        ArrayList<Crewlid> lijstVanCrewleden = CrewlidDao.getCrewleden();
        for (Crewlid huidigCrewlid : lijstVanCrewleden) {
            mijnCrewleden.addElement(huidigCrewlid);
        }
    }

    public BallonvaartAfspraak getIngevuldBallonvaartAfspraak() {
        Ballon geselecteerdeBallon = (Ballon) cbxBallon.getSelectedItem();
        Opstijgterrein geselecteerdOpstijgterrein = (Opstijgterrein) cbxOpstijgterrein.getSelectedItem();

        return new BallonvaartAfspraak(0, this.txtDatum.getText(), Integer.parseInt(this.txtAantalPassagiers.getText()), geselecteerdOpstijgterrein.getOpstijgterreinID(), geselecteerdeBallon.getBallonID());
    }
    
    

    public List<Klant> getIngevuldKlantAfspraak() {
        List<Klant> mijnGeselecteerdeKlanten = lstKlant.getSelectedValuesList();
        return mijnGeselecteerdeKlanten;
    }

    public List<Crewlid> getIngevuldCrewAfspraak() {
        List<Crewlid> mijnGeselecteerdeCrewleden = lstCrewlid.getSelectedValuesList();
        return mijnGeselecteerdeCrewleden;
    }

    public List<Piloot> getIngevuldPilootAfspraak() {
        List<Piloot> mijnGeselecteerdePiloten = lstPiloot.getSelectedValuesList();
        return mijnGeselecteerdePiloten;

    }

    public Resultaat getFormulierResultaatBallonvaartAfspraak() {
        return this.formulierResultaatBallonvaartAfspraak;
    }

    private void checkFields() {
        if (Check.checkDatum(txtDatum.getText()) && Check.checkMax5Passagiers(txtAantalPassagiers.getText()) && !lstCrewlid.isSelectionEmpty() && !lstKlant.isSelectionEmpty() && !lstPiloot.isSelectionEmpty()) {
            btnToevoegen.setEnabled(true);
        } else {
            btnToevoegen.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToevoegenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToevoegenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToevoegenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToevoegenDialogBallonvaartAfspraak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ToevoegenDialogBallonvaartAfspraak dialog = new ToevoegenDialogBallonvaartAfspraak(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JComboBox cbxBallon;
    private javax.swing.JComboBox cbxOpstijgterrein;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBallon;
    private javax.swing.JLabel lblCrewlid;
    private javax.swing.JLabel lblPiloot;
    private javax.swing.JLabel lblWarningPassagiers;
    private javax.swing.JList<Crewlid> lstCrewlid;
    private javax.swing.JList<Klant> lstKlant;
    private javax.swing.JList<Piloot> lstPiloot;
    private javax.swing.JTextField txtAantalPassagiers;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables
}
